menu:
  主页: /
  归档: /archives

logo: Free Fly

more:
  #友情链接: /links.html
  Github: https://github.com/marshalys/
  atom: /atom.xml
  #微博: http://weibo.com/XXX
  #知乎: https://www.zhihu.com/people/XXX
  #rss: /rss2.xml
  #关于我: /

about:
  title: Mars Yuan
  link: https://marshalys.github.io/

disqus_shortname:

excerpt_num: 120

footer_info: © Free Fly 2005-2083
